# Change these first
owner: maxime-sourdin # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository
runner: "[self-hosted, linux, AMD64]"
sites:
  - name: minio.sourdin.local
    url: https://minio.sourdin.local
    expectedStatusCodes:
      - 200
  - name: s3.sourdin.local
    url: https://s3.sourdin.local
    expectedStatusCodes:
      - 403
  - name: prom.sourdin.local
    url: https://prom.sourdin.local
    expectedStatusCodes:
      - 200
  - name: thanos.sourdin.local
    url: https://thanos.sourdin.local
    expectedStatusCodes:
      - 200
  - name: nexus.sourdin.local
    url: https://nexus.sourdin.local
    expectedStatusCodes:
      - 200
  - name: proxy-docker.sourdin.local
    url: https://proxy-docker.sourdin.local
    expectedStatusCodes:
      - 400
  - name: repo-docker.sourdin.local
    url: https://repo-docker.sourdin.local
    expectedStatusCodes:
      - 400
  - name: repo-pub-docker.sourdin.local
    url: https://repo-pub-docker.sourdin.local
    expectedStatusCodes:
      - 400
  - name: acme.sourdin.ovh
    url: https://acme.sourdin.ovh
    expectedStatusCodes:
      - 404
  - name: argocd.sourdin.ovh
    url: https://argocd.sourdin.ovh
    expectedStatusCodes:
      - 200
  - name: awx.sourdin.ovh
    url: https://awx.sourdin.ovh
    expectedStatusCodes:
      - 200
  - name: DNS Over HTTPS
    url: https://dns.sourdin.ovh
    expectedStatusCodes:
      - 502
  - name: grafana.sourdin.ovh
    url: https://grafana.sourdin.ovh
    expectedStatusCodes:
      - 200
  - name: nidruos.sourdin.ovh
    url: https://nidruos.sourdin.ovh
    expectedStatusCodes:
      - 200      
  - name: maxime.sourdin.ovh
    url: https://maxime.sourdin.ovh
    expectedStatusCodes:
      - 200
  - name: monitoring.sourdin.ovh
    url: https://monitoring.sourdin.ovh
    expectedStatusCodes:
      - 200
  - name: rss.sourdin.ovh
    url: https://rss.sourdin.ovh
    expectedStatusCodes:
      - 200  
  - name: rss-bridge.sourdin.ovh
    url: https://rss-bridge.sourdin.ovh
    expectedStatusCodes:
      - 200      
  - name: shaarli.sourdin.ovh
    url: https://shaarli.sourdin.ovh
    expectedStatusCodes:
      - 200   
  - name: DNS over TLS
    check: "tcp-ping"
    url: dns.sourdin.ovh
    port: 853
  - name: http
    check: "tcp-ping"
    url: appart.sourdin.ovh
    port: 80  
  - name: https
    check: "tcp-ping"
    url: appart.sourdin.ovh
    port: 443     
  - name: pve
    check: "tcp-ping"
    url: appart.sourdin.ovh
    port: 13111

  - name: biscuit.town
    url: https://biscuit.town
    expectedStatusCodes:
      - 200
  - name: ouin.land
    url: https://ouin.land
    expectedStatusCodes:
      - 200       
  - name: pipou.academy
    url: https://pipou.academy
    expectedStatusCodes:
      - 200
  - name: botsin.space
    url: https://botsin.space
    expectedStatusCodes:
      - 200
  - name: maximedurand-ux.fr
    url: https://www.maximedurand-ux.fr
    expectedStatusCodes:
      - 200   
      
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  cname: monitoring.sourdin.ovh
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SOURDIN
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
